// Package openapi scaffolds .http files from an OpenAPI 3 document: one file
// per tag, one named request per operation, path parameters as {{vars}} and
// an example body derived from the schema.
package openapi

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi/datamodel/high/base"
	v3 "github.com/pb33f/libopenapi/datamodel/high/v3"
)

// Result summarises what was generated.
type Result struct {
	Files    []string `json:"files"`
	Requests int      `json:"requests"`
	BaseURL  string   `json:"base_url"`
	EnvFile  string   `json:"env_file,omitempty"`
	Skipped  []string `json:"skipped,omitempty"`
}

// Options controls generation.
type Options struct {
	OutDir  string // directory to write into
	EnvName string // environment name for the generated http-client.env.json (default "dev")
	Force   bool   // overwrite existing files
}

// Import reads an OpenAPI document (JSON or YAML) and writes .http files.
func Import(specPath string, opts Options) (*Result, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil, err
	}
	doc, err := libopenapi.NewDocument(data)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", specPath, err)
	}
	model, buildErr := doc.BuildV3Model()
	if model == nil {
		if buildErr != nil {
			return nil, fmt.Errorf("build OpenAPI model: %w", buildErr)
		}
		return nil, fmt.Errorf("%s is not an OpenAPI 3 document", specPath)
	}
	if opts.EnvName == "" {
		opts.EnvName = "dev"
	}
	if opts.OutDir == "" {
		opts.OutDir = "."
	}
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return nil, err
	}

	res := &Result{BaseURL: "https://example.com"}
	if len(model.Model.Servers) > 0 && model.Model.Servers[0].URL != "" {
		res.BaseURL = strings.TrimRight(model.Model.Servers[0].URL, "/")
	}

	byTag := map[string][]*operation{}
	var tagOrder []string
	seenNames := map[string]int{}
	if model.Model.Paths != nil {
		for path, item := range model.Model.Paths.PathItems.FromOldest() {
			for method, op := range item.GetOperations().FromOldest() {
				o := &operation{Path: path, Method: strings.ToUpper(method), Op: op}
				o.Name = uniqueName(requestName(op, o.Method, path), seenNames)
				tag := "api"
				if len(op.Tags) > 0 {
					tag = op.Tags[0]
				}
				if _, ok := byTag[tag]; !ok {
					tagOrder = append(tagOrder, tag)
				}
				byTag[tag] = append(byTag[tag], o)
			}
		}
	}
	sort.Strings(tagOrder)

	for _, tag := range tagOrder {
		file := filepath.Join(opts.OutDir, kebab(tag)+".http")
		if _, err := os.Stat(file); err == nil && !opts.Force {
			res.Skipped = append(res.Skipped, file)
			continue
		}
		var b strings.Builder
		fmt.Fprintf(&b, "# %s — generated by `apic import` from %s. Edit freely.\n", tag, filepath.Base(specPath))
		for _, o := range byTag[tag] {
			b.WriteString(o.render())
			res.Requests++
		}
		if err := os.WriteFile(file, []byte(b.String()), 0o644); err != nil {
			return nil, err
		}
		res.Files = append(res.Files, file)
	}

	envFile := filepath.Join(opts.OutDir, "http-client.env.json")
	if _, err := os.Stat(envFile); err != nil || opts.Force {
		env := map[string]map[string]string{opts.EnvName: {"baseUrl": res.BaseURL}}
		data, _ := json.MarshalIndent(env, "", "  ")
		if err := os.WriteFile(envFile, append(data, '\n'), 0o644); err != nil {
			return nil, err
		}
		res.EnvFile = envFile
	}
	return res, nil
}

type operation struct {
	Path   string
	Method string
	Name   string
	Op     *v3.Operation
}

func (o *operation) render() string {
	var b strings.Builder
	title := o.Op.Summary
	if title == "" {
		title = o.Method + " " + o.Path
	}
	fmt.Fprintf(&b, "\n### %s\n", title)
	fmt.Fprintf(&b, "# @name %s\n", o.Name)
	if d := strings.TrimSpace(strings.SplitN(o.Op.Description, "\n", 2)[0]); d != "" && d != title {
		fmt.Fprintf(&b, "# @description %s\n", d)
	}
	fmt.Fprintf(&b, "# @assert status == %s\n", successStatus(o.Op))

	path := o.Path
	var query []string
	var headers []string
	for _, p := range o.Op.Parameters {
		if p == nil {
			continue
		}
		v := "{{" + varName(p.Name) + "}}"
		required := p.Required != nil && *p.Required
		switch p.In {
		case "path":
			path = strings.ReplaceAll(path, "{"+p.Name+"}", v)
		case "query":
			if required {
				query = append(query, p.Name+"="+v)
			} else {
				query = append(query, "# "+p.Name+"="+v)
			}
		case "header":
			line := p.Name + ": " + v
			if !required {
				line = "# " + line
			}
			headers = append(headers, line)
		}
	}
	body, contentType := exampleBody(o.Op.RequestBody)
	fmt.Fprintf(&b, "%s {{baseUrl}}%s\n", o.Method, path)
	for i, q := range query {
		sep := "&"
		if i == 0 {
			sep = "?"
		}
		if strings.HasPrefix(q, "# ") {
			fmt.Fprintf(&b, "    # %s%s  (optional)\n", sep, strings.TrimPrefix(q, "# "))
			continue
		}
		fmt.Fprintf(&b, "    %s%s\n", sep, q)
	}
	if contentType != "" {
		fmt.Fprintf(&b, "Content-Type: %s\n", contentType)
	}
	if wantsJSON(o.Op) {
		b.WriteString("Accept: application/json\n")
	}
	for _, h := range headers {
		b.WriteString(h + "\n")
	}
	if body != "" {
		b.WriteString("\n" + body + "\n")
	}
	return b.String()
}

func successStatus(op *v3.Operation) string {
	if op.Responses == nil || op.Responses.Codes == nil {
		return "200"
	}
	for code := range op.Responses.Codes.KeysFromOldest() {
		if strings.HasPrefix(code, "2") {
			return code
		}
	}
	return "200"
}

func wantsJSON(op *v3.Operation) bool {
	if op.Responses == nil || op.Responses.Codes == nil {
		return false
	}
	for r := range op.Responses.Codes.ValuesFromOldest() {
		if r != nil && r.Content != nil {
			for ct := range r.Content.KeysFromOldest() {
				if strings.Contains(ct, "json") {
					return true
				}
			}
		}
	}
	return false
}

func exampleBody(rb *v3.RequestBody) (string, string) {
	if rb == nil || rb.Content == nil {
		return "", ""
	}
	for ct, mt := range rb.Content.FromOldest() {
		if mt == nil {
			continue
		}
		var v any
		switch {
		case mt.Example != nil:
			_ = mt.Example.Decode(&v)
		case mt.Examples != nil && mt.Examples.Len() > 0:
			for ex := range mt.Examples.ValuesFromOldest() {
				if ex != nil && ex.Value != nil {
					_ = ex.Value.Decode(&v)
					break
				}
			}
		case mt.Schema != nil:
			v = exampleFromSchema(mt.Schema.Schema(), 0)
		}
		if v == nil {
			return "", ct
		}
		if strings.Contains(ct, "json") {
			data, _ := json.MarshalIndent(v, "", "  ")
			return string(data), ct
		}
		if s, ok := v.(string); ok {
			return s, ct
		}
		data, _ := json.Marshal(v)
		return string(data), ct
	}
	return "", ""
}

func exampleFromSchema(s *base.Schema, depth int) any {
	if s == nil || depth > 6 {
		return nil
	}
	if s.Example != nil {
		var v any
		if err := s.Example.Decode(&v); err == nil {
			return v
		}
	}
	if len(s.Examples) > 0 {
		var v any
		if err := s.Examples[0].Decode(&v); err == nil {
			return v
		}
	}
	if s.Default != nil {
		var v any
		if err := s.Default.Decode(&v); err == nil {
			return v
		}
	}
	if len(s.Enum) > 0 {
		var v any
		if err := s.Enum[0].Decode(&v); err == nil {
			return v
		}
	}
	for _, sub := range [][]*base.SchemaProxy{s.AllOf, s.OneOf, s.AnyOf} {
		if len(sub) > 0 {
			return exampleFromSchema(sub[0].Schema(), depth+1)
		}
	}
	typ := ""
	if len(s.Type) > 0 {
		typ = s.Type[0]
	}
	if typ == "" && s.Properties != nil && s.Properties.Len() > 0 {
		typ = "object"
	}
	switch typ {
	case "object":
		obj := &orderedObject{}
		if s.Properties != nil {
			for name, prop := range s.Properties.FromOldest() {
				obj.set(name, exampleFromSchema(prop.Schema(), depth+1))
			}
		}
		return obj
	case "array":
		if s.Items != nil && s.Items.IsA() {
			return []any{exampleFromSchema(s.Items.A.Schema(), depth+1)}
		}
		return []any{}
	case "integer":
		return 1
	case "number":
		return 1.5
	case "boolean":
		return true
	case "string":
		switch s.Format {
		case "date-time":
			return "{{$isoTimestamp}}"
		case "date":
			return "2026-01-01"
		case "email":
			return "user@example.com"
		case "uuid":
			return "{{$uuid}}"
		case "uri", "url":
			return "https://example.com"
		}
		return "string"
	}
	return nil
}

var reNonWord = regexp.MustCompile(`[^A-Za-z0-9]+`)

func kebab(s string) string {
	s = reNonWord.ReplaceAllString(s, "-")
	s = strings.Trim(strings.ToLower(s), "-")
	if s == "" {
		return "api"
	}
	return s
}

func varName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' || r == '.' || r == ' ' })
	if len(parts) == 0 {
		return "value"
	}
	parts[0] = strings.ToLower(parts[0][:1]) + parts[0][1:]
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func requestName(op *v3.Operation, method, path string) string {
	if op.OperationId != "" {
		return kebab(splitCamel(op.OperationId))
	}
	p := strings.NewReplacer("{", "by-", "}", "").Replace(path)
	return kebab(strings.ToLower(method) + " " + p)
}

var reCamel = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func splitCamel(s string) string {
	return reCamel.ReplaceAllString(s, "$1-$2")
}

func uniqueName(name string, seen map[string]int) string {
	seen[name]++
	if seen[name] == 1 {
		return name
	}
	return fmt.Sprintf("%s-%d", name, seen[name])
}

// orderedObject marshals to a JSON object keeping schema property order.
type orderedObject struct {
	keys []string
	vals map[string]any
}

func (o *orderedObject) set(k string, v any) {
	if o.vals == nil {
		o.vals = map[string]any{}
	}
	if _, ok := o.vals[k]; !ok {
		o.keys = append(o.keys, k)
	}
	o.vals[k] = v
}

func (o *orderedObject) MarshalJSON() ([]byte, error) {
	var b strings.Builder
	b.WriteByte('{')
	for i, k := range o.keys {
		if i > 0 {
			b.WriteByte(',')
		}
		kb, _ := json.Marshal(k)
		vb, err := json.Marshal(o.vals[k])
		if err != nil {
			return nil, err
		}
		b.Write(kb)
		b.WriteByte(':')
		b.Write(vb)
	}
	b.WriteByte('}')
	return []byte(b.String()), nil
}
