// Package openapi scaffolds .http files from an OpenAPI 3 document: one file
// per tag, one named request per operation, path parameters as {{vars}} and
// an example body derived from the schema.
package openapi

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Result summarises what was generated.
type Result struct {
	Files    []string `json:"files"`
	Requests int      `json:"requests"`
	BaseURL  string   `json:"base_url"`
	EnvFile  string   `json:"env_file,omitempty"`
	Skipped  []string `json:"skipped,omitempty"`
}

func (d *document) resolveServerURL(srv *yaml.Node) (string, error) {
	url := strings.TrimSpace(str(d.get(srv, "url")))
	if url == "" {
		return "", nil
	}
	defaults := map[string]string{}
	for _, v := range d.entries(d.get(srv, "variables")) {
		if def := d.get(v.value, "default"); def != nil { // absent default stays unresolved
			defaults[v.key] = str(def)
		}
	}
	out := reServerVar.ReplaceAllStringFunc(url, func(match string) string {
		name := strings.TrimSuffix(strings.TrimPrefix(match, "{"), "}")
		if v, ok := defaults[name]; ok { // an empty default is a valid value
			return v
		}
		return match
	})
	if unresolved := reServerVar.FindStringSubmatch(out); unresolved != nil {
		return "", fmt.Errorf("server URL %q has unresolved variable {%s}", url, unresolved[1])
	}
	return strings.TrimRight(out, "/"), nil
}

// Options controls generation.
type Options struct {
	OutDir  string // directory to write into
	EnvName string // environment name for the generated http-client.env.json (default "dev")
	Force   bool   // overwrite existing files
}

// Import reads an OpenAPI document (JSON or YAML) and writes .http files.
func Import(specPath string, opts Options) (*Result, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil, err
	}
	doc, err := parseDocument(data)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", specPath, err)
	}
	if opts.EnvName == "" {
		opts.EnvName = "dev"
	}
	if opts.OutDir == "" {
		opts.OutDir = "."
	}
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return nil, err
	}

	res := &Result{BaseURL: "https://example.com"}
	for _, srv := range doc.items(doc.get(doc.root, "servers")) {
		if strings.TrimSpace(str(doc.get(srv, "url"))) == "" {
			continue
		}
		baseURL, err := doc.resolveServerURL(srv)
		if err != nil {
			return nil, err
		}
		res.BaseURL = baseURL
		break
	}

	byTag := map[string][]*operation{}
	var tagOrder []string
	seenNames := map[string]int{}
	for _, pathEntry := range doc.entries(doc.get(doc.root, "paths")) {
		path := pathEntry.key
		item := doc.resolve(pathEntry.value)
		shared := doc.parameters(doc.get(item, "parameters"))
		for _, e := range doc.entries(item) {
			if !httpMethods[e.key] {
				continue
			}
			op := doc.resolve(e.value)
			o := doc.operation(path, strings.ToUpper(e.key), op, shared)
			o.Name = uniqueName(requestName(o, o.Method, path), seenNames)
			tag := "api"
			if tags := doc.items(doc.get(op, "tags")); len(tags) > 0 {
				tag = str(tags[0])
			}
			if _, ok := byTag[tag]; !ok {
				tagOrder = append(tagOrder, tag)
			}
			byTag[tag] = append(byTag[tag], o)
		}
	}
	sort.Strings(tagOrder)
	// Everything that resolves references has run by now; stop before
	// writing any file if the document was structurally broken.
	if doc.err != nil {
		return nil, fmt.Errorf("%s: %w", specPath, doc.err)
	}

	usedFiles := map[string]bool{}
	for _, tag := range tagOrder {
		base := kebab(tag)
		name := base
		for i := 2; usedFiles[name]; i++ { // foo/bar and foo-bar both kebab to foo-bar
			name = fmt.Sprintf("%s-%d", base, i)
		}
		usedFiles[name] = true
		file := filepath.Join(opts.OutDir, name+".http")
		if _, err := os.Stat(file); err == nil && !opts.Force {
			res.Skipped = append(res.Skipped, file)
			continue
		}
		var b strings.Builder
		fmt.Fprintf(&b, "# %s — generated by `apic import` from %s. Edit freely.\n", tag, filepath.Base(specPath))
		for _, o := range byTag[tag] {
			b.WriteString(o.render())
			res.Requests++
		}
		if err := os.WriteFile(file, []byte(b.String()), 0o644); err != nil {
			return nil, err
		}
		res.Files = append(res.Files, file)
	}

	envFile := filepath.Join(opts.OutDir, "http-client.env.json")
	if _, err := os.Stat(envFile); err != nil || opts.Force {
		env := map[string]map[string]string{opts.EnvName: {"baseUrl": res.BaseURL}}
		data, _ := json.MarshalIndent(env, "", "  ")
		if err := os.WriteFile(envFile, append(data, '\n'), 0o644); err != nil {
			return nil, err
		}
		res.EnvFile = envFile
	}
	return res, nil
}

var httpMethods = map[string]bool{"get": true, "put": true, "post": true, "delete": true, "options": true, "head": true, "patch": true, "trace": true}

// operation is the subset of an OpenAPI operation the generator needs.
type operation struct {
	Path        string
	Method      string
	Name        string
	OperationID string
	Summary     string
	Description string
	Params      []parameter
	Body        string // example request body, "" when none
	ContentType string
	Success     string // first 2xx response code; empty when none is declared
	WantsJSON   bool   // a response advertises a JSON content type
}

type parameter struct {
	Name     string
	In       string
	Required bool
}

// parameters reads a parameter list ($ref-able entries), in order.
func (d *document) parameters(n *yaml.Node) []parameter {
	var out []parameter
	for _, p := range d.items(n) {
		name, in := str(d.get(p, "name")), str(d.get(p, "in"))
		if name == "" || in == "" {
			continue
		}
		out = append(out, parameter{Name: name, In: in, Required: in == "path" || boolean(d.get(p, "required"))})
	}
	return out
}

func (d *document) operation(path, method string, op *yaml.Node, shared []parameter) *operation {
	o := &operation{Path: path, Method: method,
		OperationID: str(d.get(op, "operationId")), Summary: str(d.get(op, "summary")), Description: str(d.get(op, "description"))}
	// Operation parameters override path-level ones with the same name and location.
	own := d.parameters(d.get(op, "parameters"))
	for _, p := range shared {
		overridden := false
		for _, q := range own {
			if q.Name == p.Name && q.In == p.In {
				overridden = true
			}
		}
		if !overridden {
			o.Params = append(o.Params, p)
		}
	}
	o.Params = append(o.Params, own...)
	o.Body, o.ContentType = d.exampleBody(d.get(op, "requestBody"))
	responses := d.get(op, "responses")
	for _, r := range d.entries(responses) {
		if strings.HasPrefix(r.key, "2") {
			o.Success = r.key
			break
		}
	}
	for _, r := range d.entries(responses) {
		for _, ct := range d.entries(d.get(r.value, "content")) {
			if isJSON(ct.key) {
				o.WantsJSON = true
			}
		}
	}
	return o
}

func (o *operation) render() string {
	var b strings.Builder
	title := strings.Join(strings.Fields(o.Summary), " ") // one line: it is the ### heading
	if title == "" {
		title = o.Method + " " + o.Path
	}
	fmt.Fprintf(&b, "\n### %s\n", title)
	fmt.Fprintf(&b, "# @name %s\n", o.Name)
	if d := strings.TrimSpace(strings.SplitN(o.Description, "\n", 2)[0]); d != "" && d != title {
		fmt.Fprintf(&b, "# @description %s\n", d)
	}
	switch {
	case o.Success == "":
		// No 2xx declared (only `default` or error codes): nothing to assert.
	case strings.HasSuffix(o.Success, "XX") && len(o.Success) == 3:
		// Patterned key such as 2XX: assert the range instead of a literal.
		fmt.Fprintf(&b, "# @assert status >= %s00\n# @assert status < %s00\n", o.Success[:1], string(o.Success[0]+1))
	default:
		fmt.Fprintf(&b, "# @assert status == %s\n", o.Success)
	}

	path := o.Path
	var query []string
	var headers []string
	names := paramVarNames(o.Params)
	var cookies, optionalCookies []string
	for _, p := range o.Params {
		v := "{{" + names[p.In+":"+p.Name] + "}}"
		required := p.Required
		switch p.In {
		case "cookie":
			if required {
				cookies = append(cookies, p.Name+"="+v)
			} else {
				optionalCookies = append(optionalCookies, p.Name+"="+v)
			}
		case "path":
			path = strings.ReplaceAll(path, "{"+p.Name+"}", v)
		case "query":
			if required {
				query = append(query, p.Name+"="+v)
			} else {
				query = append(query, "# "+p.Name+"="+v)
			}
		case "header":
			line := p.Name + ": " + v
			if !required {
				line = "# " + line
			}
			headers = append(headers, line)
		}
	}
	body, contentType := o.Body, o.ContentType
	fmt.Fprintf(&b, "%s {{baseUrl}}%s\n", o.Method, path)
	// Active continuation lines first: the parser stops reading query
	// continuations at the first comment, so optional parameters follow.
	active := 0
	for _, q := range query {
		if strings.HasPrefix(q, "# ") {
			continue
		}
		sep := "&"
		if active == 0 {
			sep = "?"
		}
		active++
		fmt.Fprintf(&b, "    %s%s\n", sep, q)
	}
	shown := active
	for _, q := range query {
		if !strings.HasPrefix(q, "# ") {
			continue
		}
		// Commented parameters are not sent; show the separator a caller
		// would add when uncommenting them in order.
		sep := "&"
		if shown == 0 {
			sep = "?"
		}
		shown++
		fmt.Fprintf(&b, "    # %s%s  (optional)\n", sep, strings.TrimPrefix(q, "# "))
	}
	if contentType != "" {
		fmt.Fprintf(&b, "Content-Type: %s\n", contentType)
	}
	if o.WantsJSON {
		b.WriteString("Accept: application/json\n")
	}
	for _, h := range headers {
		b.WriteString(h + "\n")
	}
	if len(cookies) > 0 {
		fmt.Fprintf(&b, "Cookie: %s\n", strings.Join(cookies, "; "))
	}
	for _, c := range optionalCookies {
		fmt.Fprintf(&b, "# Cookie: %s  (optional)\n", c)
	}
	if body != "" {
		b.WriteString("\n" + body + "\n")
	}
	return b.String()
}

// exampleBody builds a request body from the first media type that can
// provide one: its example, first named example, or a value derived from
// the schema. Without any, the first media type's content type is kept.
func (d *document) exampleBody(rb *yaml.Node) (string, string) {
	mts := d.entries(d.get(rb, "content"))
	if len(mts) == 0 {
		return "", ""
	}
	for _, mt := range mts {
		ct := mt.key
		media := d.resolve(mt.value)
		var v any
		selected := true
		switch {
		case d.getRaw(media, "example") != nil:
			v = decode(d.getRaw(media, "example"))
		case firstExampleValue(d, d.get(media, "examples")) != nil:
			v = decode(firstExampleValue(d, d.get(media, "examples")))
		case d.get(media, "schema") != nil:
			v, selected = d.exampleFromSchema(d.get(media, "schema"), 0)
		default:
			selected = false
		}
		if !selected {
			continue
		}
		if isJSON(ct) {
			data, _ := json.MarshalIndent(v, "", "  ")
			return string(data), ct
		}
		if s, ok := v.(string); ok {
			return s, ct
		}
		data, _ := json.Marshal(v)
		return string(data), ct
	}
	return "", mts[0].key
}

// isJSON reports whether a media type carries JSON; names are
// case-insensitive, so application/JSON and application/problem+JSON count.
func isJSON(mediaType string) bool {
	return strings.Contains(strings.ToLower(mediaType), "json")
}

// firstExampleValue returns the `value` of the first named example that has one.
func firstExampleValue(d *document, examples *yaml.Node) *yaml.Node {
	for _, ex := range d.entries(examples) {
		if v := d.getRaw(ex.value, "value"); v != nil {
			return v
		}
	}
	return nil
}

// exampleFromSchema derives a value from a schema. ok is false only when
// nothing could be derived; a JSON null (type: null or example: null) is a
// real value.
func (d *document) exampleFromSchema(s *yaml.Node, depth int) (any, bool) {
	s = d.resolve(s)
	if s == nil || depth > 6 {
		return nil, false
	}
	if n := d.getRaw(s, "example"); n != nil {
		return decode(n), true
	}
	if ex := d.itemsRaw(d.getRaw(s, "examples")); len(ex) > 0 {
		return decode(ex[0]), true
	}
	if n := d.getRaw(s, "default"); n != nil {
		return decode(n), true
	}
	if en := d.itemsRaw(d.getRaw(s, "enum")); len(en) > 0 {
		return decode(en[0]), true
	}
	typ := schemaType(d, s)
	props := d.entries(d.get(s, "properties"))
	// allOf: every branch contributes, so object branches are merged in
	// order (later keys win) together with the properties declared here.
	if sub := d.items(d.get(s, "allOf")); len(sub) > 0 {
		merged := &orderedObject{}
		var scalar any
		object, found := false, false
		for _, branch := range sub {
			v, ok := d.exampleFromSchema(branch, depth+1)
			if !ok {
				continue
			}
			if obj, isObj := v.(*orderedObject); isObj {
				for _, k := range obj.keys {
					merged.set(k, obj.vals[k])
				}
				object = true
			} else if !found {
				scalar, found = v, true
			}
		}
		if object || typ == "object" || len(props) > 0 {
			for _, p := range props {
				v, _ := d.exampleFromSchema(p.value, depth+1)
				merged.set(p.key, v)
			}
			return merged, true
		}
		if found {
			return scalar, true
		}
	}
	for _, key := range []string{"oneOf", "anyOf"} {
		if sub := d.items(d.get(s, key)); len(sub) > 0 {
			return d.exampleFromSchema(sub[0], depth+1)
		}
	}
	if typ == "" && len(props) > 0 {
		typ = "object"
	}
	switch typ {
	case "object":
		obj := &orderedObject{}
		for _, p := range props {
			v, _ := d.exampleFromSchema(p.value, depth+1)
			obj.set(p.key, v)
		}
		return obj, true
	case "array":
		if items := d.get(s, "items"); items != nil {
			v, _ := d.exampleFromSchema(items, depth+1)
			return []any{v}, true
		}
		return []any{}, true
	case "integer":
		return 1, true
	case "number":
		return 1.5, true
	case "boolean":
		return true, true
	case "null":
		return nil, true
	case "string":
		switch str(d.get(s, "format")) {
		case "date-time":
			return "{{$isoTimestamp}}", true
		case "date":
			return "2026-01-01", true
		case "email":
			return "user@example.com", true
		case "uuid":
			return "{{$uuid}}", true
		case "uri", "url":
			return "https://example.com", true
		}
		return "string", true
	}
	return nil, false
}

// schemaType returns the schema type, taking the first non-null entry of an
// OpenAPI 3.1 type array.
func schemaType(d *document, s *yaml.Node) string {
	t := d.get(s, "type")
	if t == nil {
		return ""
	}
	if t.Kind == yaml.SequenceNode {
		for _, n := range d.items(t) {
			if v := str(n); v != "" && v != "null" {
				return v
			}
		}
		if len(d.items(t)) > 0 {
			return "null"
		}
		return ""
	}
	return str(t)
}

var reNonWord = regexp.MustCompile(`[^A-Za-z0-9]+`)
var reServerVar = regexp.MustCompile(`\{([^{}]+)\}`)

func kebab(s string) string {
	s = reNonWord.ReplaceAllString(s, "-")
	s = strings.Trim(strings.ToLower(s), "-")
	if s == "" {
		return "api"
	}
	return s
}

func varName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' || r == '.' || r == ' ' })
	if len(parts) == 0 {
		return "value"
	}
	parts[0] = strings.ToLower(parts[0][:1]) + parts[0][1:]
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func requestName(op *operation, method, path string) string {
	if op.OperationID != "" {
		return kebab(splitCamel(op.OperationID))
	}
	p := strings.NewReplacer("{", "by-", "}", "").Replace(path)
	return kebab(strings.ToLower(method) + " " + p)
}

// paramVarNames assigns a variable name to every parameter of an operation,
// disambiguating names that would otherwise collide (user-id and user_id
// both camel-case to userId) with the parameter location and, if needed, a
// counter. Keys are "<in>:<name>".
func paramVarNames(params []parameter) map[string]string {
	out := map[string]string{}
	used := map[string]bool{}
	for _, p := range params {
		base := varName(p.Name)
		name := base
		if used[name] {
			name = base + strings.ToUpper(p.In[:1]) + p.In[1:]
		}
		for i := 2; used[name]; i++ {
			name = fmt.Sprintf("%s%d", base, i)
		}
		used[name] = true
		out[p.In+":"+p.Name] = name
	}
	return out
}

var reCamel = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func splitCamel(s string) string {
	return reCamel.ReplaceAllString(s, "$1-$2")
}

func uniqueName(name string, seen map[string]int) string {
	seen[name]++
	if seen[name] == 1 {
		return name
	}
	return fmt.Sprintf("%s-%d", name, seen[name])
}

// orderedObject marshals to a JSON object keeping schema property order.
type orderedObject struct {
	keys []string
	vals map[string]any
}

func (o *orderedObject) set(k string, v any) {
	if o.vals == nil {
		o.vals = map[string]any{}
	}
	if _, ok := o.vals[k]; !ok {
		o.keys = append(o.keys, k)
	}
	o.vals[k] = v
}

func (o *orderedObject) MarshalJSON() ([]byte, error) {
	var b strings.Builder
	b.WriteByte('{')
	for i, k := range o.keys {
		if i > 0 {
			b.WriteByte(',')
		}
		kb, _ := json.Marshal(k)
		vb, err := json.Marshal(o.vals[k])
		if err != nil {
			return nil, err
		}
		b.Write(kb)
		b.WriteByte(':')
		b.Write(vb)
	}
	b.WriteByte('}')
	return []byte(b.String()), nil
}
